In [9]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [7]:
df = pd.read_csv("train_feat_df.csv")

In [8]:
t_df = df[list(df.columns)[66:(len(list(df.columns)) - 2)]]
s_df = df[list(df.columns)[:66]]
s_df["population"] = df["population"]

/Users/neevparikh/Projects/HackPrinceton/virt/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [14]:
s_df.values

array([[1.0000e+00, 1.4700e+02, 5.6098e+04, ..., 0.0000e+00, 0.0000e+00,
        2.9450e+04],
       [2.0000e+00, 1.3000e+02, 3.0625e+04, ..., 0.0000e+00, 0.0000e+00,
        5.6400e+03],
       [3.0000e+00, 8.3200e+03, 6.4093e+04, ..., 0.0000e+00, 0.0000e+00,
        3.3140e+04],
       ...,
       [4.8940e+03, 2.8793e+04, 9.5556e+04, ..., 0.0000e+00, 0.0000e+00,
               nan],
       [4.8950e+03, 1.5487e+04, 3.8305e+04, ..., 0.0000e+00, 0.0000e+00,
               nan],
       [4.8960e+03, 1.3158e+04, 2.7465e+04, ..., 0.0000e+00, 0.0000e+00,
               nan]])

In [18]:
fake = pd.read_csv("fake.csv")

In [20]:
fake.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,5000.0,2499.5000,1443.520003,0.0,1249.75,2499.5,3749.25,4999.0
Male,5000.0,36429.2858,12992.671191,13837.0,25164.50,36460.0,47645.25,58421.0
Female,5000.0,11990.5904,3591.063270,5703.0,8870.75,11954.5,15128.50,18175.0
White,5000.0,42993.3656,14704.075853,17822.0,30387.00,42839.0,55602.50,68596.0
Black Or African American,5000.0,21462.2374,8501.659315,6767.0,14144.50,21447.0,28707.75,36299.0
American Indian Or Alaskan Native,5000.0,336.4422,223.240362,0.0,122.00,332.0,535.00,731.0
Asian,5000.0,1274.2278,692.892636,80.0,671.00,1270.5,1874.25,2479.0
Native Hawaiian & Other Pacific Islander,5000.0,83.7838,59.305555,0.0,31.00,73.0,136.00,197.0
Other Race,5000.0,2506.0182,1596.404994,0.0,1109.00,2477.0,3905.50,5327.0
Two Or More Races,5000.0,7807.9234,3919.458800,1039.0,4393.75,7769.0,11207.25,14616.0
Husband Wife Family Households,5000.0,10873.0096,3862.697933,4164.0,7531.00,10819.5,14159.25,17659.0
Single Guardian,5000.0,5812.1836,2099.307730,2197.0,3991.50,5805.5,7650.75,9452.0
Singles,5000.0,8479.3676,2604.482965,3931.0,6219.00,8502.0,10731.25,12954.0
Singles With Roommate,5000.0,3803.8424,1512.498818,1188.0,2459.00,3834.0,5079.50,6424.0
Households Without Kids,5000.0,16281.9542,4829.348348,7828.0,12084.75,16377.5,20360.00,24789.0
Households With Kids,5000.0,2734.5260,979.323033,1064.0,1872.50,2755.5,3597.00,4418.0
Worked Full-time With Earnings,5000.0,22314.6672,7703.558051,8889.0,15704.00,22254.0,29069.25,35610.0
Worked Part-time With Earnings,5000.0,5141.5162,1576.614886,2442.0,3752.00,5150.0,6522.00,7904.0
No Earnings,5000.0,23630.0408,9083.423696,7887.0,15845.75,23395.5,31359.00,39858.0
"< $25,000",5000.0,6283.1292,1661.278008,3356.0,4856.75,6298.5,7734.00,9160.0
"$25,000-$44,999",5000.0,5453.1306,1901.219393,2176.0,3796.50,5458.5,7126.50,8746.0
"$45,000-$59,999",5000.0,2293.0130,1314.093519,0.0,1149.00,2310.0,3417.25,4577.0
"$60,000-$99,999",5000.0,4297.7260,2462.404507,2.0,2196.50,4297.5,6422.25,8553.0
"$100,000-$149,999",5000.0,2826.2370,1624.091868,0.0,1441.00,2787.0,4259.50,5683.0
"$150,000-$199,999",5000.0,447.7712,199.981275,110.0,272.00,446.0,620.00,793.0
"$200,000+",5000.0,522.4386,280.984751,35.0,281.00,523.0,767.25,1010.0
Less Than High School Diploma,5000.0,15664.1246,6928.698400,3613.0,9735.50,15569.0,21830.00,27547.0
High School Graduate,5000.0,20758.5404,7107.467275,8571.0,14500.50,20936.5,27022.25,33042.0
Associate's Degree,5000.0,2506.5244,1432.425356,0.0,1261.00,2523.0,3724.50,4958.0
Bachelor's Degree,5000.0,2945.6846,1022.045148,1189.0,2064.75,2918.5,3852.00,4728.0
...,...,...,...,...,...,...,...,...
day11,5000.0,0.4990,0.500049,0.0,0.00,0.0,1.00,1.0
day12,5000.0,0.4960,0.500034,0.0,0.00,0.0,1.00,1.0
day13,5000.0,0.5156,0.499807,0.0,0.00,1.0,1.00,1.0
day14,5000.0,0.4908,0.499965,0.0,0.00,0.0,1.00,1.0
day15,5000.0,0.5058,0.500016,0.0,0.00,1.0,1.00,1.0
day16,5000.0,0.4986,0.500048,0.0,0.00,0.0,1.00,1.0
day17,5000.0,0.5060,0.500014,0.0,0.00,1.0,1.00,1.0
day18,5000.0,0.4950,0.500025,0.0,0.00,0.0,1.00,1.0
day19,5000.0,0.5150,0.499825,0.0,0.00,1.0,1.00,1.0
day2,5000.0,0.5012,0.500049,0.0,0.00,1.0,1.00,1.0
day20,5000.0,0.4970,0.500041,0.0,0.00,0.0,1.00,1.0
day21,5000.0,0.4934,0.500006,0.0,0.00,0.0,1.00,1.0
day22,5000.0,0.4922,0.499989,0.0,0.00,0.0,1.00,1.0
day23,5000.0,0.4920,0.499986,0.0,0.00,0.0,1.00,1.0
day24,5000.0,0.5064,0.500009,0.0,0.00,1.0,1.00,1.0
day25,5000.0,0.4940,0.500014,0.0,0.00,0.0,1.00,1.0
day26,5000.0,0.5060,0.500014,0.0,0.00,1.0,1.00,1.0
day27,5000.0,0.4986,0.500048,0.0,0.00,0.0,1.00,1.0
day28,5000.0,0.4970,0.500041,0.0,0.00,0.0,1.00,1.0
day29,5000.0,0.5076,0.499992,0.0,0.00,1.0,1.00,1.0
day3,5000.0,0.5064,0.500009,0.0,0.00,1.0,1.00,1.0
day30,5000.0,0.4968,0.500040,0.0,0.00,0.0,1.00,1.0
day31,5000.0,0.5036,0.500037,0.0,0.00,1.0,1.00,1.0
day4,5000.0,0.4974,0.500043,0.0,0.00,0.0,1.00,1.0
day5,5000.0,0.4992,0.500049,0.0,0.00,0.0,1.00,1.0
day6,5000.0,0.4892,0.499933,0.0,0.00,0.0,1.00,1.0
day7,5000.0,0.4976,0.500044,0.0,0.00,0.0,1.00,1.0
day8,5000.0,0.4980,0.500046,0.0,0.00,0.0,1.00,1.0
day9,5000.0,0.5076,0.499992,0.0,0.00,1.0,1.00,1.0
year,5000.0,2015.9822,1.419819,2014.0,2015.00,2016.0,2017.00,2018.0