In [21]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

columns_keep =  ['population_density', 'median_household_income', 'Male', 'Female', 'White', 'Black Or African American', 'American Indian Or Alaskan Native', 'Asian', 'Native Hawaiian & Other Pacific Islander', 'Other Race', '< $25,000', '$25,000-$44,999', '$45,000-$59,999', '$60,000-$99,999', '$100,000-$149,999', '$150,000-$199,999', '$200,000+', 'Less Than High School Diploma', 'High School Graduate', "Associate's Degree", "Bachelor'sDegree", "Master's Degree", 'Professional School Degree', 'Doctorate Degree', 'Enrolled In Public School', 'Enrolled In Private School', 'Not Enrolled In School', 'April', 'August', 'December', 'February', 'January', 'July', 'June', 'March', 'May', 'November', 'October', 'September', 'day1', 'day10', 'day11', 'day12', 'day13', 'day14', 'day15', 'day16', 'day17', 'day18', 'day19', 'day2', 'day20', 'day21', 'day22', 'day23', 'day24', 'day25', 'day26', 'day27', 'day28', 'day29', 'day3', 'day30', 'day31', 'day4', 'day5', 'day6', 'day7', 'day8', 'day9', 'year']

In [23]:
df = pd.read_csv("train_feat_df.csv")
df

,Unnamed: 0,population_density,median_household_income,Under 5,05-Sep,Oct-14,15-19,20-24,25-29,30-34,...,day30,day31,day4,day5,day6,day7,day8,day9,year,population
0,1,147,56098,3813,3480,3131,2806,2508,2873,2739,...,0,0,0,0,0,0,0,0,2014,29450.0
1,2,130,30625,1276,1145,1027,2028,5133,2084,1186,...,0,0,0,0,0,0,0,0,2014,5640.0
2,3,8320,64093,50,23,23,920,2149,2401,1828,...,1,0,0,0,0,0,0,0,2014,33140.0
3,6,9850,97158,863,771,726,794,767,1408,1406,...,0,0,0,0,0,0,0,0,2015,36050.0
4,7,808,39659,357,339,327,317,416,447,363,...,0,0,0,0,0,0,0,0,2017,27660.0
5,8,3153,77156,802,763,716,716,554,751,775,...,0,0,0,1,0,0,0,0,2017,710.0
6,9,5247,61188,1496,1343,1391,1602,1475,1303,1228,...,0,0,0,0,0,0,0,0,2016,36670.0
7,10,1924,36598,1386,1249,1185,922,907,1028,1064,...,0,0,0,0,0,0,0,0,2015,109280.0
8,11,9,58094,35,31,35,39,20,21,22,...,0,0,0,0,0,0,0,0,2014,44160.0
9,12,842,50526,1555,1568,1454,1230,1194,1540,1323,...,0,0,0,0,0,0,0,0,2014,17630.0
10,13,3158,65420,4399,4686,4691,4220,2795,3350,3908,...,0,0,0,0,0,0,0,0,2015,710.0
11,14,9989,85672,1143,1225,1504,1632,1580,1476,1284,...,0,0,0,0,0,0,0,0,2015,9300.0
12,15,145,33056,824,704,694,718,660,624,581,...,0,0,0,0,0,0,0,0,2017,18030.0
13,17,1583,21397,26,36,14,22,51,44,29,...,0,0,0,0,0,0,0,0,2014,9420.0
14,18,6213,70300,172,116,64,447,1049,1500,903,...,1,0,0,0,0,0,0,0,2018,14730.0
15,19,3678,48234,807,702,754,844,1006,1056,928,...,0,0,0,0,0,0,0,0,2016,22460.0
16,20,28793,95556,148,68,65,155,548,1206,779,...,0,0,0,0,0,0,0,0,2017,10560.0
17,21,9062,68707,76,28,16,222,787,1070,720,...,0,0,0,0,0,0,0,0,2014,10850.0
18,22,64,36080,749,704,702,944,872,748,592,...,0,0,0,0,0,0,0,0,2016,3510.0
19,23,461,30468,714,617,504,2884,6196,1955,1080,...,0,0,0,0,0,0,0,0,2018,16880.0
20,24,28793,95556,148,68,65,155,548,1206,779,...,0,0,0,1,0,0,0,0,2018,10700.0
21,25,7617,40380,166,144,129,622,1511,1170,709,...,0,0,0,0,0,0,0,0,2014,3660.0
22,26,23,45640,137,142,130,214,364,331,253,...,0,0,0,0,0,0,0,0,2014,21510.0
23,27,1950,29818,730,546,501,961,1342,870,593,...,0,0,0,1,0,0,0,0,2015,680.0
24,28,9062,68707,76,28,16,222,787,1070,720,...,0,0,1,0,0,0,0,0,2016,8850.0
25,29,1077,88295,56,56,52,43,26,41,82,...,0,0,0,1,0,0,0,0,2015,25480.0
26,30,4525,42337,726,576,514,695,1088,1157,920,...,0,0,0,0,0,0,0,0,2016,11240.0
27,31,1159,20227,15,7,2,5,34,58,38,...,0,0,0,0,0,0,0,0,2016,17890.0
28,32,4654,56388,205,70,54,304,1136,1430,1046,...,0,0,0,0,0,0,0,0,2017,34980.0
29,35,7758,36614,1135,1118,1165,1253,1242,1186,1064,...,0,0,0,0,0,1,0,0,2014,24640.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4176,4862,1880,50177,224,193,129,213,468,747,464,...,0,0,0,0,0,0,0,0,2016,NaN
4177,4863,4406,31519,1494,1449,1370,1608,1430,1204,1080,...,0,1,0,0,0,0,0,0,2017,NaN
4178,4864,6947,54417,52,39,29,29,123,278,203,...,0,0,0,0,0,0,0,0,2016,NaN
4179,4865,436,37152,1910,1771,1740,1706,2155,1747,1610,...,0,0,0,0,0,0,0,0,2014,NaN
4180,4866,6069,43404,1096,852,773,892,1561,2476,2243,...,0,0,0,0,0,0,0,0,2015,NaN
4181,4867,28793,95556,148,68,65,155,548,1206,779,...,0,0,0,0,0,0,1,0,2017,NaN
4182,4869,28793,95556,148,68,65,155,548,1206,779,...,0,0,0,0,0,0,0,0,2017,NaN
4183,4870,24914,76962,38,9,6,130,332,554,352,...,0,0,0,0,0,0,0,0,2014,NaN
4184,4872,5127,45784,321,305,285,360,495,709,524,...,0,0,0,0,0,0,0,0,2016,NaN
4185,4873,5542,26391,1368,1135,969,996,1155,1326,1273,...,0,0,0,0,0,0,0,1,2014,NaN
4186,4874,104,47684,25,24,23,22,10,17,17,...,0,0,0,0,1,0,0,0,2014,NaN
4187,4876,4867,36458,6,9,18,192,471,536,400,...,0,0,0,0,0,0,0,0,2016,NaN
4188,4878,2464,19231,64,85,50,159,379,343,138,...,0,0,0,0,0,0,0,0,2016,NaN
4189,4879,439,47232,1451,1207,1083,1404,1931,1303,897,...,0,0,0,0,0,0,0,0,2014,NaN
4190,4881,5542,26391,1368,1135,969,996,1155,1326,1273,...,0,0,0,0,0,0,0,0,2015,NaN
4191,4882,16306,35097,2922,2646,2765,2827,2531,2350,2211,...,0,0,0,0,0,1,0,0,2017,NaN
4192,4883,4867,36458,6,9,18,192,471,536,400,...,0,0,0,0,0,0,0,0,2017,NaN
4193,4884,5127,45784,321,305,285,360,495,709,524,...,0,0,0,0,0,0,0,0,2017,NaN
4194,4885,136,26113,689,674,604,723,585,523,534,...,0,0,0,0,0,0,0,0,2017,NaN
4195,4886,4356,16069,137,74,61,233,535,559,550,...,0,0,0,0,0,0,0,0,2017,NaN
4196,4887,5827,65393,587,693,757,827,658,586,546,...,0,0,0,0,0,0,0,0,2014,NaN
4197,4888,226,27342,1727,1346,1315,1446,3019,2335,1542,...,0,0,0,0,0,0,0,0,2016,NaN
4198,4889,4356,16069,137,74,61,233,535,559,550,...,0,0,0,0,0,0,0,0,2017,NaN
4199,4890,1880,18894,98,76,35,105,292,303,263,...,0,0,0,0,0,0,0,0,2018,NaN
4200,4891,2715,41948,2032,2071,1982,2013,1754,1794,1668,...,0,0,0,0,0,0,0,0,2014,NaN
4201,4892,7447,24609,1781,1696,1627,1782,1676,1756,1640,...,0,0,0,0,0,0,0,1,2017,NaN
4202,4893,112,35030,711,718,726,739,629,596,595,...,0,0,0,1,0,0,0,0,2015,NaN
4203,4894,28793,95556,148,68,65,155,548,1206,779,...,0,0,0,0,0,0,0,0,2014,NaN
4204,4895,15487,38305,2166,1981,1764,1948,2361,2489,2418,...,0,0,0,0,0,0,1,0,2015,NaN
4205,4896,13158,27465,387,338,267,324,1001,1457,858,...,0,0,0,0,0,0,0,0,2015,NaN

In [8]:
t_df = df[list(df.columns)[66:(len(list(df.columns)) - 2)]]
s_df = df[list(df.columns)[:66]]
s_df["population"] = df["population"]

/Users/neevparikh/Projects/HackPrinceton/virt/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [14]:
s_df.values

array([[1.0000e+00, 1.4700e+02, 5.6098e+04, ..., 0.0000e+00, 0.0000e+00,
        2.9450e+04],
       [2.0000e+00, 1.3000e+02, 3.0625e+04, ..., 0.0000e+00, 0.0000e+00,
        5.6400e+03],
       [3.0000e+00, 8.3200e+03, 6.4093e+04, ..., 0.0000e+00, 0.0000e+00,
        3.3140e+04],
       ...,
       [4.8940e+03, 2.8793e+04, 9.5556e+04, ..., 0.0000e+00, 0.0000e+00,
               nan],
       [4.8950e+03, 1.5487e+04, 3.8305e+04, ..., 0.0000e+00, 0.0000e+00,
               nan],
       [4.8960e+03, 1.3158e+04, 2.7465e+04, ..., 0.0000e+00, 0.0000e+00,
               nan]])

In [18]:
fake = pd.read_csv("fake.csv")

In [20]:
fake.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,5000.0,2499.5000,1443.520003,0.0,1249.75,2499.5,3749.25,4999.0
Male,5000.0,36429.2858,12992.671191,13837.0,25164.50,36460.0,47645.25,58421.0
Female,5000.0,11990.5904,3591.063270,5703.0,8870.75,11954.5,15128.50,18175.0
White,5000.0,42993.3656,14704.075853,17822.0,30387.00,42839.0,55602.50,68596.0
Black Or African American,5000.0,21462.2374,8501.659315,6767.0,14144.50,21447.0,28707.75,36299.0
American Indian Or Alaskan Native,5000.0,336.4422,223.240362,0.0,122.00,332.0,535.00,731.0
Asian,5000.0,1274.2278,692.892636,80.0,671.00,1270.5,1874.25,2479.0
Native Hawaiian & Other Pacific Islander,5000.0,83.7838,59.305555,0.0,31.00,73.0,136.00,197.0
Other Race,5000.0,2506.0182,1596.404994,0.0,1109.00,2477.0,3905.50,5327.0
Two Or More Races,5000.0,7807.9234,3919.458800,1039.0,4393.75,7769.0,11207.25,14616.0
Husband Wife Family Households,5000.0,10873.0096,3862.697933,4164.0,7531.00,10819.5,14159.25,17659.0
Single Guardian,5000.0,5812.1836,2099.307730,2197.0,3991.50,5805.5,7650.75,9452.0
Singles,5000.0,8479.3676,2604.482965,3931.0,6219.00,8502.0,10731.25,12954.0
Singles With Roommate,5000.0,3803.8424,1512.498818,1188.0,2459.00,3834.0,5079.50,6424.0
Households Without Kids,5000.0,16281.9542,4829.348348,7828.0,12084.75,16377.5,20360.00,24789.0
Households With Kids,5000.0,2734.5260,979.323033,1064.0,1872.50,2755.5,3597.00,4418.0
Worked Full-time With Earnings,5000.0,22314.6672,7703.558051,8889.0,15704.00,22254.0,29069.25,35610.0
Worked Part-time With Earnings,5000.0,5141.5162,1576.614886,2442.0,3752.00,5150.0,6522.00,7904.0
No Earnings,5000.0,23630.0408,9083.423696,7887.0,15845.75,23395.5,31359.00,39858.0
"< $25,000",5000.0,6283.1292,1661.278008,3356.0,4856.75,6298.5,7734.00,9160.0
"$25,000-$44,999",5000.0,5453.1306,1901.219393,2176.0,3796.50,5458.5,7126.50,8746.0
"$45,000-$59,999",5000.0,2293.0130,1314.093519,0.0,1149.00,2310.0,3417.25,4577.0
"$60,000-$99,999",5000.0,4297.7260,2462.404507,2.0,2196.50,4297.5,6422.25,8553.0
"$100,000-$149,999",5000.0,2826.2370,1624.091868,0.0,1441.00,2787.0,4259.50,5683.0
"$150,000-$199,999",5000.0,447.7712,199.981275,110.0,272.00,446.0,620.00,793.0
"$200,000+",5000.0,522.4386,280.984751,35.0,281.00,523.0,767.25,1010.0
Less Than High School Diploma,5000.0,15664.1246,6928.698400,3613.0,9735.50,15569.0,21830.00,27547.0
High School Graduate,5000.0,20758.5404,7107.467275,8571.0,14500.50,20936.5,27022.25,33042.0
Associate's Degree,5000.0,2506.5244,1432.425356,0.0,1261.00,2523.0,3724.50,4958.0
Bachelor's Degree,5000.0,2945.6846,1022.045148,1189.0,2064.75,2918.5,3852.00,4728.0
...,...,...,...,...,...,...,...,...
day11,5000.0,0.4990,0.500049,0.0,0.00,0.0,1.00,1.0
day12,5000.0,0.4960,0.500034,0.0,0.00,0.0,1.00,1.0
day13,5000.0,0.5156,0.499807,0.0,0.00,1.0,1.00,1.0
day14,5000.0,0.4908,0.499965,0.0,0.00,0.0,1.00,1.0
day15,5000.0,0.5058,0.500016,0.0,0.00,1.0,1.00,1.0
day16,5000.0,0.4986,0.500048,0.0,0.00,0.0,1.00,1.0
day17,5000.0,0.5060,0.500014,0.0,0.00,1.0,1.00,1.0
day18,5000.0,0.4950,0.500025,0.0,0.00,0.0,1.00,1.0
day19,5000.0,0.5150,0.499825,0.0,0.00,1.0,1.00,1.0
day2,5000.0,0.5012,0.500049,0.0,0.00,1.0,1.00,1.0
day20,5000.0,0.4970,0.500041,0.0,0.00,0.0,1.00,1.0
day21,5000.0,0.4934,0.500006,0.0,0.00,0.0,1.00,1.0
day22,5000.0,0.4922,0.499989,0.0,0.00,0.0,1.00,1.0
day23,5000.0,0.4920,0.499986,0.0,0.00,0.0,1.00,1.0
day24,5000.0,0.5064,0.500009,0.0,0.00,1.0,1.00,1.0
day25,5000.0,0.4940,0.500014,0.0,0.00,0.0,1.00,1.0
day26,5000.0,0.5060,0.500014,0.0,0.00,1.0,1.00,1.0
day27,5000.0,0.4986,0.500048,0.0,0.00,0.0,1.00,1.0
day28,5000.0,0.4970,0.500041,0.0,0.00,0.0,1.00,1.0
day29,5000.0,0.5076,0.499992,0.0,0.00,1.0,1.00,1.0
day3,5000.0,0.5064,0.500009,0.0,0.00,1.0,1.00,1.0
day30,5000.0,0.4968,0.500040,0.0,0.00,0.0,1.00,1.0
day31,5000.0,0.5036,0.500037,0.0,0.00,1.0,1.00,1.0
day4,5000.0,0.4974,0.500043,0.0,0.00,0.0,1.00,1.0
day5,5000.0,0.4992,0.500049,0.0,0.00,0.0,1.00,1.0
day6,5000.0,0.4892,0.499933,0.0,0.00,0.0,1.00,1.0
day7,5000.0,0.4976,0.500044,0.0,0.00,0.0,1.00,1.0
day8,5000.0,0.4980,0.500046,0.0,0.00,0.0,1.00,1.0
day9,5000.0,0.5076,0.499992,0.0,0.00,1.0,1.00,1.0
year,5000.0,2015.9822,1.419819,2014.0,2015.00,2016.0,2017.00,2018.0

In [25]:
df['2014']

KeyError: '2014'